### ISSUE TITLE
Potential dependency conflicts between loggertodb and htimeseries

### ISSUE THREAD

**Issue by NeolithEra** [openmeteo/loggertodb#30]
Hi, as shown in the following full dependency graph of **_loggertodb_**, **_loggertodb_** requires **_htimeseries <2,>=1_**, **_loggertodb_** requires **_enhydris-api-client <1,>=0.3_** (**_enhydris-api-client 0.5.1_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_enhydris-api-client 0.5.1_** transitively introduces **_htimeseries >=1.1.1,<3_**.

Obviously, there are multiple version constraints set for **_htimeseries_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_htimeseries 1.1.2_** (i.e., the newest version satisfying constraint **_<2,>=1_**) is the actually installed version.

Although the first found package version **_htimeseries 1.1.2_** just satisfies the later dependency constraint （**_htimeseries <2,>=1_**), such installed version is very close to the upper bound of the version constraint of htimeseries specified by **_enhydris-api-client 0.5.1_**. 

Once **_enhydris-api-client_** upgrades，its newest version will be installed. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_enhydris-api-client_** version introduces a higher version of **_htimeseries_**, violating its another version constraint **_<2,>=1_**.

According to the release history of enhydris-api-client, it habitually upgrates Htimeseries in its recent releases. For instance, **_enhydris-api-client 0.3_** upgrated Htimeseries’s constraint from **_>=0.2.0 to >=1,<2_**,**_enhydris-api-client 0.5.0_** upgrated Htimeseries’s constraint from **_>=1,<2 to >=1.1.1,<2_**, and **_enhydris-api-client 0.5.1_** upgrated Htimeseries’s constraint from **_>=1.1.1,<2 to >=1.1.1,<3_**. 

As such, it is a warm warning of a potential dependency conflict issue for loggertodb.

### Dependency tree
```
loggertodb  - 1.0.0
| +- click(install version:7.1.2 version range:<8,>=7.0)
| +- enhydris-api-client(install version:0.5.1 version range:<1,>=0.3)
| | +- htimeseries(install version:1.1.2 version range:>=1.1.1,<3)
| | | +- iso8601(install version:0.1.12 version range:*)
| | | +- pandas(install version:1.0.3 version range:>=0.20)
| | | +- textbisect(install version:0.1.0 version range:*)
| | +- iso8601(install version:0.1.12 version range:*)
| | +- pandas(install version:1.0.3 version range:>=0.20)
| | +- requests(install version:2.23.0 version range:<3,>=1)
| | | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | | +- idna(install version:2.9 version range:>=2.5,<3)
| | | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| +- htimeseries(install version:1.1.2 version range:<2,>=1)
| | +- iso8601(install version:0.1.12 version range:*)
| | +- pandas(install version:1.0.3 version range:>=0.20)
| | +- textbisect(install version:0.1.0 version range:*)
| +- iso8601(install version:0.1.12 version range:*)
| +- simpletail(install version:1.0.0 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_htimeseries_** to be **_>=1_**.
2.	Remove your direct dependency **_htimeseries_**, and use the **_htimeseries_** transitively introduced by **_enhydris-api-client_**.
3.	Change your direct dependency **_enhydris-api-client_** to be **_>=0.3,<=0.5.1_**.
@aptiko  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by aptiko** [comment]
@NeolithEra Thanks! Could you explain how you came to be interested in loggertodb? Are you using it in a project?

**Comment by aptiko** [comment]
@NeolithEra Is this some script you have created that scans github for repos that are facing that exact issue and files an issue? Please don't waste my time.
