### ISSUE TITLE
Create Windows executable

### ISSUE THREAD

**Issue by aptiko** [openmeteo/loggertodb#4]
Child of aptiko/openhi#60.

The solution for this is to use pyinstaller + NSIS.

**Comment by aptiko** [comment]
This isn't very hard, but it isn't trivial either. Let's leave it out until we have a concrete case of needing to run loggertodb on Windows.

One difficulty is that at the moment pyinstaller can package only "normal" Python scripts, whereas in this case the script is generated by `setup.py` through the `entry_points` argument. Searching the net will reveal that this is a yet unsolved problem in pyinstaller for which [a workaround exists](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Setuptools-Entry-Point). However the workaround is complicated and maybe a simpler solution is to create a "normal" Python script to be used for Windows only (same as was done in pthelma).

**Comment by dimitrisal** [comment]
Hello any news on installer? is there any workaround for windows?

**Comment by aptiko** [comment]
@dimitrisal Could you explain why you are interested in this?

**Comment by dimitrisal** [comment]
@aptiko We have 2 davis that was sending data in openmeteo with pthelma but we saw now that we get an error 403.

**Comment by aptiko** [comment]
@dimitrisal This 403 error is unrelated. Please email me at antonis@antonischristofides.com for more.
